### ISSUE TITLE
Keep ratio when scaling?

### ISSUE THREAD

**Issue by Tofandel** [itgalaxy/favicons#334] opened 2021-09-29 12:12 UTC
Is there any option or way to have the image fitted keeping the proportions when generating the favicon other than to resize the image directly?

Currently if the image is not square it gives bad results

**Comment by andy128k** [comment] 2021-11-07 20:16
I was not able to reproduce the issue. See #360 
It may happen that the issue was already fixed in master branch.

@Tofandel May you check it again?

**Comment by jbroutier** [comment] 2022-02-15 19:54
Hello,

I have encountered the same issue when using a non-square svg file without a `viewBox` attribute on the <svg> tag. Adding the attribute on the same exact file solved the issue.

**Comment by andy128k** [comment] 2022-02-15 19:57
@jbroutier which version do you use? May you provide a reproducible test?

**Comment by jbroutier** [comment] 2022-02-15 21:06
I'm using version 6.2.2.

Sure, here it is: https://github.com/jbroutier/favicons-334 Run both `src/with-viewbox.js` & `src/without-viewbox.js` and compare the generated files in the corresponding output folder.

In the second case some of the generated favicons are not centered and have an abnormally huge padding on some sides. It looks like it's broken only when the target favicon size is bigger than the source file size.

**Comment by andy128k** [comment] 2022-02-16 00:10
@jbroutier Thanks!

**Closed** 2022-02-16 22:34 UTC
